apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-back
spec:
    replicas: REPLICA
    selector:
        matchLabels:
            app: node-back
    template:
        metadata:
            labels:
                app: node-back
        spec:
            containers:
                - name: node-back
                  image: DOCKER_IMAGE:TAG
                  imagePullPolicy: Always
                  ports:
                  - containerPort: 8000
                  env:
                    - name: MONGO_DB
                      valueFrom:
                          configMapKeyRef:
                              name: db-config
                              key: db_name
                    - name: MONGO_HOST
                      value: mongo
                    - name: MONGO_PORT
                      valueFrom:
                          configMapKeyRef:
                              name: db-config
                              key: db_port