apiVersion: v1
kind: Service
metadata: 
  name: mongo
  labels:
    app: mongo-db
spec:
  type: NodePort
  selector: 
    app: mongo-db
  ports:
   - protocol: TCP
     nodePort: 30003
     port: 27017