apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pvc 
  labels:
    name: mongo-pvc 
spec:
  capacity:
    storage: 100M
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-monica
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc 
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  volumeName: mongo-pvc